language: ruby

rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1
  - ruby-head
  - rbx-2.1.1
  #- jruby-18mode
  #- jruby-19mode

os:
  - linux
  - osx

branches:
  only:
    - master

gemfile:
  - Gemfile

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2
